services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ecoride}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ecoride}
      POSTGRES_USER: ${POSTGRES_USER:-ecoride}
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '${POSTGRES_DB:-ecoride}', '-U', '${POSTGRES_USER:-ecoride}']
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - name: http
        target: 8000
        published: ${HTTP_PORT:-8000}
        protocol: tcp
    volumes:
      - .:/var/www/html
      - symfony_var:/var/www/html/var
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint-app.sh:ro
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      HTTP_PORT: ${HTTP_PORT:-8000}
      DEFAULT_URI: http://${SERVER_NAME:-localhost}:${HTTP_PORT:-8000}
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-dev_secret}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      POSTGRES_USER: ${POSTGRES_USER:-ecoride}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ecoride}
      POSTGRES_DB: ${POSTGRES_DB:-ecoride}
      POSTGRES_VERSION: ${POSTGRES_VERSION:-16}
      POSTGRES_CHARSET: ${POSTGRES_CHARSET:-utf8}
      DATABASE_URL: postgresql://${POSTGRES_USER:-ecoride}:${POSTGRES_PASSWORD:-ecoride}@database:5432/${POSTGRES_DB:-ecoride}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
      MONGODB_URI: ${MONGODB_URI_DOCKER:-mongodb://mongodb:27017}
      MONGODB_DB: ${MONGODB_DB:-ecoride}
      MAILERSEND_API_KEY: ${MAILERSEND_API_KEY:-}
      MAIL_FROM: ${MAIL_FROM:-}
      MAIL_TO: ${MAIL_TO:-}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
    depends_on:
      database:
        condition: service_healthy
      mongodb:
        condition: service_started

  adminer:
    image: adminer:latest
    ports:
      - name: adminer
        target: 8080
        published: ${ADMINER_PORT:-8080}
        protocol: tcp
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      database:
        condition: service_healthy

###> doctrine/mongodb-odm-bundle ###
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    environment:
      - MONGODB_INITDB_DATABASE=${MONGODB_DB:-ecoride}
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}
    volumes:
      - mongodb_data:/data/db:rw
###< doctrine/mongodb-odm-bundle ###

volumes:
  database_data:
  symfony_var:

###> doctrine/mongodb-odm-bundle ###
  mongodb_data:
###< doctrine/mongodb-odm-bundle ###
