services:
  database:
    ports:
      - name: postgres
        target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp

###> doctrine/mongodb-odm-bundle ###
  mongodb:
    ports:
      - name: mongo
        target: 27017
        published: ${MONGODB_PORT:-27017}
        protocol: tcp
###< doctrine/mongodb-odm-bundle ###
