<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260515153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user profile type, vehicle seats and driver preferences for US8.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE \"user\" ADD profile_type VARCHAR(32) DEFAULT 'passenger' NOT NULL");
        $this->addSql('ALTER TABLE car ADD seats_available INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE car ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE car ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CAR_REGISTRATION_NUMBER ON car (registration_number)');
        $this->addSql('CREATE TABLE driver_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, allow_smoking BOOLEAN NOT NULL, allow_animals BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DRIVER_PREFERENCE_USER ON driver_preference (user_id)');
        $this->addSql('CREATE TABLE custom_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, driver_preference_id INT NOT NULL, label VARCHAR(120) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CUSTOM_PREFERENCE_DRIVER ON custom_preference (driver_preference_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CUSTOM_PREFERENCE_LABEL_PER_DRIVER ON custom_preference (driver_preference_id, label)');
        $this->addSql('ALTER TABLE driver_preference ADD CONSTRAINT FK_DRIVER_PREFERENCE_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE custom_preference ADD CONSTRAINT FK_CUSTOM_PREFERENCE_DRIVER FOREIGN KEY (driver_preference_id) REFERENCES driver_preference (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE custom_preference DROP CONSTRAINT FK_CUSTOM_PREFERENCE_DRIVER');
        $this->addSql('ALTER TABLE driver_preference DROP CONSTRAINT FK_DRIVER_PREFERENCE_USER');
        $this->addSql('DROP TABLE custom_preference');
        $this->addSql('DROP TABLE driver_preference');
        $this->addSql('DROP INDEX UNIQ_CAR_REGISTRATION_NUMBER');
        $this->addSql('ALTER TABLE car DROP seats_available');
        $this->addSql('ALTER TABLE car DROP created_at');
        $this->addSql('ALTER TABLE car DROP updated_at');
        $this->addSql('ALTER TABLE "user" DROP profile_type');
    }
}
